# Step 1: Use a lightweight JDK image
FROM openjdk:17-jdk-slim

# Step 2: Add a label (optional)
LABEL maintainer="you@example.com"

# Step 3: Set the working directory
WORKDIR /app

# Step 4: Copy the JAR from target folder into the container
COPY target/FirstDockerProject-0.0.1-SNAPSHOT.jar FirstDockerProject-0.0.1-SNAPSHOT.jar

# Step 5: Expose the port your app uses
EXPOSE 8080

# Step 6: Run the JAR file
ENTRYPOINT ["java","-jar","FirstDockerProject-0.0.1-SNAPSHOT.jar"]
